### ISSUE TITLE
LAND

### ISSUE THREAD

**Issue by akipaki293** [PiweeX/HogRealms#15]
Srediti land komande kao što su land delete, transferowner...

**Comment by PiweeX** [comment]
Taj deo plugina se rešava putem floodgate plugina, stanje ovoga se može pratiti u ddos isue-u koji je trenutno aktivan, svakako obavestiću i ovde kad sredimo i ukoliko uspemo, nisam siguran u to da li je to do toga ali deluje da jeste i konsultovao sam se sa Konfixom

**Comment by PiweeX** [comment]
```
[21:09:21 WARN]: [Lands] Failed to execute GUI click. Name: land_various
[21:09:21 WARN]: java.lang.NoClassDefFoundError: org/geysermc/floodgate/api/FloodgateApi
[21:09:21 WARN]:        at Lands-6.2.3.jar//me.angeschossen.lands.birQG.HIHAp.NeDiR.NeDiR.NeDiR.gObcv.NeDiR(?:28)
[21:09:21 WARN]:        at Lands-6.2.3.jar//me.angeschossen.lands.osTNW.gObcv.gbbUs.gbbUs.osTNW(?:49)
[21:09:21 WARN]:        at Lands-6.2.3.jar//me.angeschossen.lands.birQG.RkBKZ.gObcv.NeDiR.gbbUs.NeDiR(?:35)
[21:09:21 WARN]:        at Lands-6.2.3.jar//me.angeschossen.lands.birQG.RkBKZ.gbbUs.osTNW.NeDiR(?:112)
[21:09:21 WARN]:        at Lands-6.2.3.jar//me.angeschossen.lands.birQG.kImqv.gObcv.NeDiR(?:46)
[21:09:21 WARN]:        at com.destroystokyo.paper.event.executor.StaticMethodHandleEventExecutor.execute(StaticMethodHandleEventExecutor.java:38)
[21:09:21 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76)
[21:09:21 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[21:09:21 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:671)
[21:09:21 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2861)
[21:09:21 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:58)
[21:09:21 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(PacketPlayInWindowClick.java:23)
[21:09:21 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[21:09:21 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[21:09:21 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[21:09:21 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[21:09:21 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1401)
[21:09:21 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
[21:09:21 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[21:09:21 WARN]:        at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1378)
[21:09:21 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1371)
[21:09:21 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[21:09:21 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1349)
[21:09:21 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1231)
[21:09:21 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:317)
[21:09:21 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[21:09:21 WARN]: Caused by: java.lang.ClassNotFoundException: org.geysermc.floodgate.api.FloodgateApi
[21:09:21 WARN]:        ... 26 more
```

**Comment by akipaki293** [comment]
Dodati još chunkova za claimanje po mogućnosti beskonačno

**Comment by akipaki293** [comment]
> ti nijesi sav svoj

sto

**Comment by akipaki293** [comment]
> ti nijesi sav svoj

imam sve i svasta za claim
