### ISSUE TITLE
PlaceHolderi

### ISSUE THREAD

**Issue by PiweeX** [PiweeX/HogRealms#9]
Greška sa PlaceHolderAPI-em, igrači ovih dana prijavljivali da od jutra posle restarta placeholderi u četu i sa strane ne rade

**Comment by PiweeX** [comment]
![download](https://user-images.githubusercontent.com/33425430/173929936-bafe87df-17b4-44aa-89df-d8c7321d790c.png)


21:06:26 WARN]: [PlaceholderAPI] Task #1387 for PlaceholderAPI v2.11.1 generated an exception
org.bukkit.plugin.messaging.ChannelNotRegisteredException: Attempted to send a plugin message through the unregistered channel `BungeeCord'.
        at org.bukkit.plugin.messaging.StandardMessenger.validatePluginMessage(StandardMessenger.java:544) ~[pufferfish-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.entity.CraftPlayer.sendPluginMessage(CraftPlayer.java:1876) ~[pufferfish-1.18.2.jar:git-Pufferfish-68]
        at com.extendedclip.papi.bungeeexpansion.BungeeCordExpansion.getServers(BungeeCordExpansion.java:108) ~[?:?]
        at com.extendedclip.papi.bungeeexpansion.BungeeCordExpansion.access$100(BungeeCordExpansion.java:45) ~[?:?]
        at com.extendedclip.papi.bungeeexpansion.BungeeCordExpansion$1.run(BungeeCordExpansion.java:201) ~[?:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[pufferfish-1.18.2.jar:git-Pufferfish-68]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[pufferfish-1.18.2.jar:git-Pufferfish-68]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1533) ~[pufferfish-1.18.2.jar:git-Pufferfish-68]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[pufferfish-1.18.2.jar:git-Pufferfish-68]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1457) ~[pufferfish-1.18.2.jar:git-Pufferfish-68]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1227) ~[pufferfish-1.18.2.jar:git-Pufferfish-68]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:317) ~[pufferfish-1.18.2.jar:git-Pufferfish-68]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by PiweeX** [comment]
HoloExtansion stavljen u .jarr i unloadovan posle nekoliko sati, više nema ovog erora gore sa slike ali ima od Papija idalje

**Comment by PiweeX** [comment]
Problem da placeholderi jutru ne rade se pojavio posle ovog problema, ne znam kako će biti rešen ali potrudićemo se

**Comment by PiweeX** [comment]
I dalje imamo problem da se jutru pokvare pa sve do podne dok se ne ukuca komanda.. ovo je veliki problem i utiče na nove igrače, mora se rešiti što pre

**Comment by PiweeX** [comment]
Placeholderi su nakon prepunjenja memorije fixani tako što su ponovo instalirani preko komande u igri, ovo je pokušavano ranije ali eto bitno da je rešeno

0432
